[build]
  base = "react-admin-panel/"
  publish = "build"
  command = "CI=false yarn build"
  functions = "src/functions"
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
